export const seoTerms = [
  "chat naturista",
  "chat naturalista",
  "naturist chat",
  "nudist chat",
  "naturist video chat",
  "anonymous nudist chat",
  "chat nudista",
  "videochat naturista",
  "chat naturista +18",
  "anonymous chat without login",
  "random video chat",
  "talk to strangers",
  "Omegle",
  "Omeagle",
  "Omegle alternative",
  "Chatroulette",
  "OmeTV",
  "chat anônimo sem cadastro",
  "chat aleatório",
  "videochat aleatório",
  "conversar com estranhos",
  "chat sem login",
  "alternativa ao Omegle",
  "chat anónimo sin registro",
  "videochat aleatorio",
  "hablar con extraños",
  "chat sin cuenta",
  "alternativa a Omegle",
  "chat anonyme sans inscription",
  "chat vidéo aléatoire",
  "parler à des inconnus",
  "anonymer Videochat",
  "zufälliger Chat",
  "chat anonima senza registrazione",
  "videochat casuale",
  "free random chat",
  "no signup video chat",
  "stranger video call",
  "chat ao vivo",
  "videochamada aleatória",
] as const;

export const heroTerms = [
  "anonymous chat without login",
  "chat anônimo sem cadastro",
  "chat anónimo sin registro",
  "Omegle alternative",
  "random video chat",
  "talk to strangers",
  "videochat aleatório",
  "chat sem login",
  "Chatroulette",
  "Omeagle",
  "chat naturista",
  "naturist chat",
  "nudist chat",
  "chat naturalista",
] as const;
